// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytoumzloidipvybszbsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0b3VtemxvaWRpcHZ5YnN6YnNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MzE2OTgsImV4cCI6MjA2OTUwNzY5OH0.FOmOnMyDezASjd6OrDEJkj2Tw3bXK9d59WyE7acrrPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});